version: '3'
services:

    #
    # """  PHP Services  """
    #
    #

    # PHP 8
    php:
        build:
            context: .
            dockerfile: ./_docker/app/Dockerfile
        image: php:8.1-fpm
        container_name: php81
        user: "1000:1000"
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: php81
            SERVICE_TAGS: dev
        working_dir: /home/dentclub/www
        volumes:
            - ./:/home/dentclub/www
            - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - common_network

    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/home/dentclub/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - common_network

    #Node Service
    node:
        image: node:21
        container_name: node
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/home/dentclub/www
        networks:
            - common_network

    #MySQL Services
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dentclub
            MYSQL_ROOT_PASSWORD: vasea14
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./_docker/db:/var/lib/mysql/
            - ./-docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - common_network

    #Redis Service
    redis:
        image: "redis:7.2.4"
        container_name: redis
        restart: unless-stopped
        tty: true
        command: redis-server
        ports:
            - "6379:6379"
        networks:
            - common_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: vasea14
        depends_on:
            - db
        ports:
            - 3001:80
        networks:
            - common_network

#Docker Networks
networks:
    common_network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local